# Generated by Django 2.0.4 on 2018-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(null=True),
        ),
    ]
