# Generated by Django 2.0.4 on 2018-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20180415_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
